# Generated by Django 5.0.3 on 2024-03-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True)),
                ('image', models.ImageField(upload_to='todo/')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('d', 'done'), ('i', 'in_process'), ('p', 'planning')], default='d', max_length=1)),
            ],
            options={
                'verbose_name': 'TODO',
                'verbose_name_plural': 'TODOS',
            },
        ),
    ]
